//
// Created by Lake on 2023/1/19.
//

#include "capture.h"
#include <stdio.h>
#include <pcap.h>

int run_capture(const char * dev) {
    printf("start capture\n");
    pcap_t* pcap;
    const u_char* pkt;
    struct pcap_pkthdr ph;
    char ebuf[PCAP_ERRBUF_SIZE];
    pcap = pcap_open_live(dev, 65535, 0, 0, ebuf);
    if (!pcap) {
        fprintf(stderr, "%s\n", ebuf);
        return -1;
    }

    pcap_dumper_t *dumper = pcap_dump_open(pcap, "./cap.pcap");

    if (pcap_loop(pcap, 2000, &pcap_dump, (u_char *)dumper) < 0) {
        /*
            * Print out appropriate text, followed by the error message
            * generated by the packet capture library.
            */
        printf("Error reading packets from interface %s", "en0");
        return 8;
    }

    pcap_dump_flush(dumper);
    pcap_dump_close(dumper);
    pcap_close(pcap);

    printf("stoped capture\n");
    return 0;
}

int main() {
    run_capture("en0");
}